name: Java CI
run-name: ${{ github.actor }} is running a verification test 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -   name: Checkout code
        uses: actions/checkout@v3
        id: checkout

    -   name: Print checkout directory contents
        run: ls -la ${{ steps.checkout.outputs.working-directory }}

    -   name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

    -   name: Grant execute permission for mvnw
        run: chmod +x mvnw

    -   name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-

    -   name: Build and test with Maven
        run: mvn clean test